create table if not exists public.portal_clientes (
  slug text primary key, nome text not null, guia_completo boolean not null, guia_caracteres int not null default 0,
  atualizado_em timestamptz not null default now());
alter table public.portal_clientes enable row level security;
insert into public.portal_clientes (slug, nome, guia_completo, guia_caracteres) values
('acesso_saude', 'Acesso Saúde', true, 3354),
('amazon_open_mall', 'Amazon Open Mall', true, 3489),
('animativ', 'ANIMATIV', true, 3541),
('arena_tintas', 'Arena Tintas', true, 3426),
('automaster', 'AUTOMASTER', true, 4960),
('ba_eletrica', 'BA Elétrica', true, 3356),
('bap', 'BAP', true, 3399),
('best_car', 'BEST CAR', true, 3918),
('bigazine', 'BIGAZINE', false, 3650),
('braga_acessorios', 'Braga Acessórios', true, 3079),
('braga_motors', 'Braga Motors', true, 3064),
('braga_motos', 'Braga Motos', true, 3041),
('braga_veiculos', 'BRAGA VEÍCULOS', true, 3295),
('caa_tintas_express', 'CAA Tintas Express', true, 1933),
('cdl_manaus', 'CDL Manaus', true, 3530),
('constroi_incorporadora', 'CONSTRÓI INCORPORADORA', true, 2959),
('distribuidora_pneu_forte', 'Distribuidora Pneu Forte', true, 3669),
('djb_transportes', 'DJB Transportes', true, 3694),
('doctor_saude', 'Doctor + Saúde', true, 4023),
('don_watches', 'DON Watches', true, 3622),
('equador', 'EQUADOR', true, 3324),
('fiat_via_marconi', 'FIAT Via Marconi', true, 3787),
('fogas', 'FOGÁS', false, 3463),
('hage_alimentos', 'Hage Alimentos', true, 3639),
('hospital_santa_julia', 'Hospital Santa Júlia', true, 3441),
('inforcell', 'InForcell', true, 4019),
('kiffer', 'KIFFER', true, 3475),
('kl_rent_a_car_electrics', 'KL Rent a Car Electrics', true, 3365),
('leapmotor_via_marconi', 'Leapmotor | Via Marconi', true, 3976),
('linvest', 'Linvest', false, 3919),
('maravilha_motos', 'Maravilha Motos', true, 4109),
('millennium_shopping', 'Millennium Shopping', true, 4151),
('move', 'Move', true, 2619),
('murano_veiculos', 'Murano Veículos', true, 3066),
('nova_era', 'Nova Era', true, 3091),
('ola_casa_nova', 'Olá Casa Nova', true, 4026),
('orla92', 'ORLA92', true, 2900),
('patio_gourmet', 'Pátio Gourmet', true, 3260),
('pmz_escola_para_mecanicos', 'PMZ Escola para Mecânicos', true, 4286),
('pmz_pecas_e_pneus', 'PMZ Peças e Pneus', true, 3615),
('pneu_express', 'Pneu eXpress', true, 3940),
('pneu_forte', 'Pneu Forte', true, 3468),
('prestex', 'PRESTEX', true, 3214),
('rodrix_motos', 'Rodrix Motos', true, 3172),
('royal_enfield', 'Royal Enfield', false, 3047),
('santo_remedio_drogarias', 'Santo Remédio Drogarias', true, 3630),
('shizen_honda', 'Shizen Honda', true, 3476),
('smile_pneus', 'Smile Pneus', true, 3563),
('steel_port', 'STEEL PORT', true, 4308),
('tropical_atacadao', 'Tropical Atacadão', true, 3375),
('tropical_multiloja', 'Tropical Multiloja', true, 3882),
('unipar', 'UNIPAR', true, 2846),
('vanguarda_growth_company', 'Vanguarda Growth Company', true, 2798),
('vbot', 'VBOT', true, 3511),
('voike', 'Voiké', true, 3397)
on conflict (slug) do update set nome=excluded.nome, guia_completo=excluded.guia_completo, guia_caracteres=excluded.guia_caracteres, atualizado_em=now();
